name: checkbox-iotr2
summary: Checkbox tool for the iotr2.5 test automation project
description: |
  Checkbox tool for the iotr2.5 test automation project
version: 1.0dev

grade: stable
confinement: strict

apps:
  checkbox-cli:
    command: bin/checkbox-cli-wrapper
    plugs: &standard [home, network-bind, hardware-observe, bluez, bluetooth-control,
      gpio, modem-manager, mount-observe, network-manager, pulseaudio, serial-port,
      system-observe, tpm, udisks2]
  configure:
    command: bin/configure
  test-runner:
    command: bin/test-runner
    plugs: *standard
  ioter5-automated:
    command: bin/ioter5-automated
    plugs: *standard

parts:
  checkbox-support-dev:
    source-tag: ""
  checkbox-ng-dev:
    source-tag: ""
  plainbox-provider-resource:
    source-tag: ""
    after: [checkbox-support-dev, checkbox-ng-dev]
  plainbox-provider-checkbox:
    source-tag: ""
    after: [plainbox-provider-resource]
  plainbox-provider-snappy:
    source-tag: ""
    after: [plainbox-provider-checkbox]
  checkbox-provider-vienna:
    plugin: plainbox-provider
    source: ./checkbox-provider-vienna
    after: [plainbox-provider-snappy]
  parts-meta-info:
    after: [plainbox-provider-snappy]
  launchers:
    plugin: dump
    source: launchers/
    organize:
      '*': bin/
  config-variables:
    plugin: dump
    source: config/

