name: itron-automated-test
version: 1.0 
summary: iotr2.5 test automation
description: iotr2.5 E2E test automation
grade: devel
confinement: devmode

apps:
    test-runner:
        command: bin/test-runner
    itron-wan:
        command: bin/wan-mode
    itron-edge:
        command: bin/edge-mode
    itron-client:
        command: bin/client-mode
    daily-test-execution:
        command: daily_execution_test
        daemon: simple
        restart-condition: always

parts:
    plainbox-provider-automation:
        plugin: plainbox-provider
        source: ./plainbox-provider-automation
        after: [checkbox-ng]
    launchers:
        plugin: dump
        source: launchers/
        organize:
            '*': bin/
    checkbox-ng:
        plugin: python
        source: https://git.launchpad.net/checkbox-ng
        source-type: git
        build-packages:
            - build-essential
        python-packages:
            - XlsxWriter
            - Jinja2
            - idna==2.7
    config-variable:
       plugin: dump
       source: config
    my-service:
       plugin: dump
       source: daily_check
